7 review CRUD
NaeverStore/NaeverStore pull request #12
Opened 2024-01-23 08:26 UTC by tkfkadldy

컨트롤 임시 작성
서비스 TODO처리

2024-01-23 08:42 UTC, tlsgkdns commented on src/main/kotlin/com/naever/store/domain/review/dto/ReviewResponse.kt
> +    val createdAt : CreationTimestamp
이거 작동하나여?

2024-01-26 07:31 UTC, adorecamus requested changes
수정 요청한 부분 반영해주시면 감사하겠습니다!!ㅎㅎ

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/controller/ReviewController.kt
> +    }
주문상품 하나당 하나의 리뷰만 작성하는 게 보통이니까.. getReviewList보다는 getReview 가 좋지 않을까요..?! (만약 사용자 아이디로 모든 리뷰를 조회하는 경우나 상품 아이디로 모든 리뷰를 조회하는 경우라면 list를 붙여야 하겠지만..ㅎㅎ)

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/dto/CreateReviewRequest.kt
>      val rating : String,
rating 데이터 타입이 int 여야 하지 않을까요..?!!

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/dto/ReviewResponse.kt
> +    val rating: String,
ratie 데이터 타입이 int 여야 하는 것이 아닌지..!

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/dto/UpdateReviewRequest.kt
> +    val rating : String,
요기도 int 여야..!

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/model/Review.kt
>          val rating : String,
요기도 데이터 타입 int로..!

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/model/Review.kt
> +}
요건 개인적인 의견인데 ReviewResponse에서 Entity(Review)를 DTO(ReviewResponse)로 바꾸는 로직을 넣어주는 게 좋을 것 같습니당..ㅎㅎ 만약 DTO 의 필드명이 수정되거나 추가된다면 Entity 도 수정이 필요하게 되니까요..?!

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/service/ReviewServiceImpl.kt
> +    override fun getAllReviewList(orderItemId: Long): ReviewResponse{
list 가 아니라 단건 조회니까 이름을 바꿔주시면 좋겠습니당ㅎㅎ

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/service/ReviewServiceImpl.kt
> +
review.user.id 와 로그인한 사용자 아이디가 일치하는지 확인하고, 불일치하면 forbiddenException 발생시키면 좋겠습니당ㅎㅎ

2024-01-26 07:31 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/service/ReviewServiceImpl.kt
> +//        orderItem.deleteReview(review)
제가 작업하다 주석 처리 해버렸네요..!ㅠㅠ 상품 코드 보시면서 soft-delete 를 시도해보셨으면 좋겠습니다..!!
review entity 에 SQLRestriction 어노테이션을 달아서 is_deleted 컬럼이 true 가 아닐 때만 조회하도록 하고, 삭제 시에는 review 의 is_deleted 컬럼을 true 로 바꾸고 저장하는 게 어떨까요..?!

2024-01-26 10:56 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/service/ReviewServiceImpl.kt
> +//        orderItem.deleteReview(review)
이 부분 모르시겠으면 저한테 알려주세용ㅎㅎ

2024-01-26 17:53 UTC, adorecamus requested changes
메서드 이름 변경, 수정 시 인가, 논리적 삭제도 잘 구현해주셨네요!!
삭제 시 인가 부분 수정해서 다시 올려주시면 감사하겠습니다!!ㅎㅎ

2024-01-26 17:53 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/review/service/ReviewServiceImpl.kt
> +           throw ForbiddenException(review.user.id!!, "OrderItem", orderItemId)
updateReview 에서와 마찬가지로 review.user.id 와 로그인한 사용자 id 를 비교해야 할 듯합니다!ㅎㅎ

2024-01-26 17:53 UTC, adorecamus commented on src/main/kotlin/com/naever/store/domain/user/dto/UserRegisterRequest.kt
> +    //@field:Pattern(regexp = "(?=.*[0-9])(?=.*[a-zA-Z])(?=.*\\W)(?=\\S+$)", message = "비밀번호는 영문 대소문자, 숫자, 특수문자를 사용하세요.")
테스트하신 뒤에는 이 주석 처리도 해제해서 올려주세용!ㅎㅎ

2024-01-28 09:24 UTC, merged